apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"calico-kube-controllers"},"rules":[{"apiGroups":[""],"resources":["nodes"],"verbs":["watch","list","get"]},{"apiGroups":[""],"resources":["pods"],"verbs":["get","list","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["ipreservations"],"verbs":["list"]},{"apiGroups":["crd.projectcalico.org"],"resources":["blockaffinities","ipamblocks","ipamhandles"],"verbs":["get","list","create","update","delete","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["ippools"],"verbs":["list","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["hostendpoints"],"verbs":["get","list","create","update","delete"]},{"apiGroups":["crd.projectcalico.org"],"resources":["clusterinformations"],"verbs":["get","list","create","update","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["kubecontrollersconfigurations"],"verbs":["get","create","update","watch"]}]}
    creationTimestamp: "2023-02-24T13:02:11Z"
    name: calico-kube-controllers
    resourceVersion: "135"
    uid: 8bee9a36-ad2e-4646-9210-aa9b2aaa7110
  rules:
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ipreservations
    verbs:
    - list
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - blockaffinities
    - ipamblocks
    - ipamhandles
    verbs:
    - get
    - list
    - create
    - update
    - delete
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ippools
    verbs:
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - hostendpoints
    verbs:
    - get
    - list
    - create
    - update
    - delete
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - clusterinformations
    verbs:
    - get
    - list
    - create
    - update
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - kubecontrollersconfigurations
    verbs:
    - get
    - create
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"calico-node"},"rules":[{"apiGroups":[""],"resourceNames":["calico-node"],"resources":["serviceaccounts/token"],"verbs":["create"]},{"apiGroups":[""],"resources":["pods","nodes","namespaces"],"verbs":["get"]},{"apiGroups":["discovery.k8s.io"],"resources":["endpointslices"],"verbs":["watch","list"]},{"apiGroups":[""],"resources":["endpoints","services"],"verbs":["watch","list","get"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["get"]},{"apiGroups":[""],"resources":["nodes/status"],"verbs":["patch","update"]},{"apiGroups":["networking.k8s.io"],"resources":["networkpolicies"],"verbs":["watch","list"]},{"apiGroups":[""],"resources":["pods","namespaces","serviceaccounts"],"verbs":["list","watch"]},{"apiGroups":[""],"resources":["pods/status"],"verbs":["patch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["globalfelixconfigs","felixconfigurations","bgppeers","globalbgpconfigs","bgpconfigurations","ippools","ipreservations","ipamblocks","globalnetworkpolicies","globalnetworksets","networkpolicies","networksets","clusterinformations","hostendpoints","blockaffinities","caliconodestatuses"],"verbs":["get","list","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["ippools","felixconfigurations","clusterinformations"],"verbs":["create","update"]},{"apiGroups":["crd.projectcalico.org"],"resources":["caliconodestatuses"],"verbs":["update"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["get","list","watch"]},{"apiGroups":["crd.projectcalico.org"],"resources":["bgpconfigurations","bgppeers"],"verbs":["create","update"]},{"apiGroups":["crd.projectcalico.org"],"resources":["blockaffinities","ipamblocks","ipamhandles"],"verbs":["get","list","create","update","delete"]},{"apiGroups":["crd.projectcalico.org"],"resources":["ipamconfigs"],"verbs":["get"]},{"apiGroups":["crd.projectcalico.org"],"resources":["blockaffinities"],"verbs":["watch"]},{"apiGroups":["apps"],"resources":["daemonsets"],"verbs":["get"]}]}
    creationTimestamp: "2023-02-24T13:02:11Z"
    name: calico-node
    resourceVersion: "138"
    uid: 39194f89-1139-446b-a1e7-bc603c747878
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - calico-node
    resources:
    - serviceaccounts/token
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - pods
    - nodes
    - namespaces
    verbs:
    - get
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    verbs:
    - watch
    - list
    - get
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - nodes/status
    verbs:
    - patch
    - update
  - apiGroups:
    - networking.k8s.io
    resources:
    - networkpolicies
    verbs:
    - watch
    - list
  - apiGroups:
    - ""
    resources:
    - pods
    - namespaces
    - serviceaccounts
    verbs:
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods/status
    verbs:
    - patch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - globalfelixconfigs
    - felixconfigurations
    - bgppeers
    - globalbgpconfigs
    - bgpconfigurations
    - ippools
    - ipreservations
    - ipamblocks
    - globalnetworkpolicies
    - globalnetworksets
    - networkpolicies
    - networksets
    - clusterinformations
    - hostendpoints
    - blockaffinities
    - caliconodestatuses
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ippools
    - felixconfigurations
    - clusterinformations
    verbs:
    - create
    - update
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - caliconodestatuses
    verbs:
    - update
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - bgpconfigurations
    - bgppeers
    verbs:
    - create
    - update
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - blockaffinities
    - ipamblocks
    - ipamhandles
    verbs:
    - get
    - list
    - create
    - update
    - delete
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - ipamconfigs
    verbs:
    - get
  - apiGroups:
    - crd.projectcalico.org
    resources:
    - blockaffinities
    verbs:
    - watch
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"coredns"},"rules":[{"apiGroups":[""],"resources":["endpoints","services","pods","namespaces"],"verbs":["list","watch"]},{"apiGroups":["discovery.k8s.io"],"resources":["endpointslices"],"verbs":["list","watch"]}]}
    creationTimestamp: "2023-02-24T16:57:06Z"
    name: coredns
    resourceVersion: "18748"
    uid: 201431db-a182-4224-b667-c214e86e4314
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    - pods
    - namespaces
    verbs:
    - list
    - watch
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"microk8s-hostpath"},"rules":[{"apiGroups":[""],"resources":["persistentvolumeclaims"],"verbs":["list","get","watch","update"]},{"apiGroups":[""],"resources":["persistentvolumes"],"verbs":["list","get","update","watch","create","delete"]},{"apiGroups":[""],"resources":["endpoints"],"verbs":["list","get","update","watch","create","delete"]},{"apiGroups":[""],"resources":["events"],"verbs":["create","list","patch"]},{"apiGroups":["storage.k8s.io"],"resources":["storageclasses"],"verbs":["list","watch"]},{"apiGroups":[""],"resources":["pods"],"verbs":["get","create","delete"]},{"apiGroups":[""],"resources":["nodes"],"verbs":["get"]}]}
    creationTimestamp: "2023-06-18T16:14:54Z"
    name: microk8s-hostpath
    resourceVersion: "3960071"
    uid: 81342078-e88b-4d54-b01a-ab77670a83e4
  rules:
  - apiGroups:
    - ""
    resources:
    - persistentvolumeclaims
    verbs:
    - list
    - get
    - watch
    - update
  - apiGroups:
    - ""
    resources:
    - persistentvolumes
    verbs:
    - list
    - get
    - update
    - watch
    - create
    - delete
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - list
    - get
    - update
    - watch
    - create
    - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - list
    - patch
  - apiGroups:
    - storage.k8s.io
    resources:
    - storageclasses
    verbs:
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - create
    - delete
  - apiGroups:
    - ""
    resources:
    - nodes
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"kube-schedule-scaler"},"rules":[{"apiGroups":[""],"resources":["namespaces"],"verbs":["get","list"]},{"apiGroups":["apps"],"resources":["deployments"],"verbs":["get","list"]},{"apiGroups":["apps"],"resources":["deployments/scale"],"verbs":["patch"]},{"apiGroups":["autoscaling","extensions"],"resources":["horizontalpodautoscalers"],"verbs":["get","list","patch"]}]}
    creationTimestamp: "2023-06-27T14:00:18Z"
    name: kube-schedule-scaler
    resourceVersion: "4343729"
    uid: bebb5476-e774-4c8a-9c97-0ff37803ae27
  rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - get
    - list
  - apiGroups:
    - apps
    resources:
    - deployments
    verbs:
    - get
    - list
  - apiGroups:
    - apps
    resources:
    - deployments/scale
    verbs:
    - patch
  - apiGroups:
    - autoscaling
    - extensions
    resources:
    - horizontalpodautoscalers
    verbs:
    - get
    - list
    - patch
kind: List
metadata:
  resourceVersion: ""
