apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"kube-schedule-scaler"},"name":"kube-schedule-scaler","namespace":"kube-schedule-scaler"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"kube-schedule-scaler"}},"template":{"metadata":{"labels":{"app":"kube-schedule-scaler"}},"spec":{"containers":[{"image":"public.ecr.aws/citizensadvice/kube-schedule-scaler:master","imagePullPolicy":"Always","name":"kube-schedule-scaler","resources":{"limits":{"memory":"128Mi"},"requests":{"cpu":"50m","memory":"128Mi"}}}],"securityContext":{"runAsUser":1000},"serviceAccountName":"kube-schedule-scaler"}}}}
    creationTimestamp: "2023-06-27T14:00:18Z"
    generation: 1
    labels:
      app: kube-schedule-scaler
    name: kube-schedule-scaler
    namespace: kube-schedule-scaler
    resourceVersion: "4345734"
    uid: ff08ee2d-2375-4865-b100-d73c149808ea
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: kube-schedule-scaler
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: kube-schedule-scaler
      spec:
        containers:
        - image: public.ecr.aws/citizensadvice/kube-schedule-scaler:master
          imagePullPolicy: Always
          name: kube-schedule-scaler
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext:
          runAsUser: 1000
        serviceAccount: kube-schedule-scaler
        serviceAccountName: kube-schedule-scaler
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - lastTransitionTime: "2023-06-27T14:00:18Z"
      lastUpdateTime: "2023-06-27T14:00:33Z"
      message: ReplicaSet "kube-schedule-scaler-7fbf956b6b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2023-06-27T14:20:10Z"
      lastUpdateTime: "2023-06-27T14:20:10Z"
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
