apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gerenciador-conta-pi
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gerenciador-conta-pi
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gerenciador-conta-pi-batch
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gerenciador-conta-pi-batch
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gerenciador-conta-pi-consulta
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gerenciador-conta-pi-consulta 
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gi-agendamento
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gi-agendamento 
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gi-baldes-dict 
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gi-baldes-dict  
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gi-baldes-icom
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gi-baldes-icom  
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gi-indireto-gestao
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gi-indireto-gestao  
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gi-monitor-processos-automaticos
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gi-monitor-processos-automaticos  
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-gi-registro-contabil
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gi-registro-contabil 
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-batch
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-batch
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-contabilidade
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-contabilidade
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-ebank
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-ebank
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-enderecamento
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-enderecamento
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-envio-icom
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-envio-icom
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-extracao
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-extracao
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-infobank
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-infobank
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-limites
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-limites
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-mensagens
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-mensagens
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-metricas
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-metricas
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70


---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-polling-dict
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-polling-dict
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-polling-icom
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-polling-icom
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-processos-automaticos
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-processos-automaticos
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-qrcode
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-qrcode
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-registro-mensagem
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-registro-mensagem
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-rendafixa
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-rendafixa
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-reprocessamento-falha
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-reprocessamento-falha
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-sincronismo
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-sincronismo
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-tratamento-falha
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-tratamento-falha
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-instantaneo-triagem-icom
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-instantaneo-triagem-icom
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-integra-notificacao
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-integra-notificacao
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-processamento-icom
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-processamento-icom
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-processamento-icom-gestao
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-processamento-icom-gestao
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api-pagamento-processamento-icom-offline
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-pagamento-processamento-icom-offline
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-autbank-pix-mssd
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autbank-pix-mssd
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-front-participante-indireto
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-participante-indireto
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-front-web-gerenciador-conta-pi
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-web-gerenciador-conta-pi
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-oauth-server
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oauth-server
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-redis
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: redis
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-vault-unseal
  namespace: autbank-pix
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vault-unseal
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70



