apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-pagamento-instantaneo-monitor
  namespace: autbank-pix
  labels:
    app: api-pagamento-instantaneo
spec:
  selector:
    matchLabels:
      app: api-pagamento-instantaneo
  endpoints:
    - port: http
  metricRelabelings:
    - sourceLabels: [__name__]
      regex:  network_receive_bytes_api_pagamento_instantaneo_teste
      action: keep
